logging:
  file:
    name: logs/eureka.log
    max-size: 500MB
    max-history: 10
  level:
    root: info
    org.msa.eurekaserver: debug

spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
    register-with-eureka: false
    fetch-registry: false