apiVersion: apps/v1
kind : Deployment
metadata:
  name: item-service
  namespace: micro
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: item-service
  template:
    metadata:
      labels:
        app: item-service
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: item-service
          image: sora5341/microservice-for-k8s:0.0.6
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: h2-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_DRIVER-CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  name: h2-config
                  key: SPRING_DATASOURCE_DRIVER-CLASS_NAME
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: h2-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: h2-config
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_H2_CONSOLE_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: h2-config
                  key: SPRING_H2_CONSOLE_ENABLED
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: h2-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
            - name: SPRING_JPA_SHOW_SQL
              valueFrom:
                configMapKeyRef:
                  name: h2-config
                  key: SPRING_JPA_SHOW_SQL
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 10"]
          startupProbe:
            httpGet:
              path: /probe/startup
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /probe/ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 1
            successThreshold: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /probe/live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 1
            failureThreshold: 3
