apiVersion: v1
kind: Service
metadata:
  name: item-service-service
  namespace: micro
spec:
  type: ClusterIP
  selector:
    app: item-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080