apiVersion: apps/v1
kind : Deployment
metadata:
  name: eureka-server
  namespace: micro
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: eureka-server
          image: sora5341/eurekaserver-for-k8s:0.0.3