FROM openjdk:17-jdk-alpine AS builder

COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY src src

# 설정 파일을 복사
COPY src/main/resources/config /app/config


RUN chmod +x ./gradlew
RUN dos2unix ./gradlew
RUN ./gradlew bootJar

FROM openjdk:17-jdk-alpine
WORKDIR /app

# JAR 파일을 복사
COPY --from=builder build/libs/*.jar /app/app.jar

# 설정 파일을 복사
COPY src/main/resources/config /app/config

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
