apiVersion: v1
kind: Pod
metadata:
    name: my-localhost-pod
spec:
    containers:
        - name: nginx-container
          image: nginx
        - name: curl-container
          image: curlimages/curl
          command: ["sh", "-c", "sleep 180"]
