logging:
  file:
    name: logs/gateway.log
    max-size: 500MB
    max-history: 10
  level:
    root: info
    org.msa.gatewayserver: debug

# gateway 의 proxy 설정
spring:
  cloud:
    gateway:
      # routes 는 클라이언트의 요청 URI 에 대해서
      # 어떤 마이크로 서비스로 요청 데이터를 전달할 것인지와 같은
      # 라우팅 관련 설정
      routes:
        # id 는 라우팅을 위한 식별 id 임.
        - id: item-service
          # uri 는 이동할 마이크로 서비스 명임.
          # lb 는 load balancing 의 약자임.
          # item-service 는 유레카 서버에 등록된 마이크로 서비스명임.
          uri: lb://item-service
          # predicates 의 path 설정은 실제 요청 들어온 uri 주소임.
          # /v1/item/ 으로 시작하는 요청이 들어왔을 때
          # item-servoce 마이크로 서비스로 요청을 전달하겠다는 의미임.
          predicates:
            - Path=/v1/item/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka