apiVersion: v1
kind: Pod
metadata:
    name: my-simple-pod
spec:
    restartPolicy: OnFailure
    containers:
        - name: my-container
          #image: nginx:1.24
          image: busybox
          command: ["sh", "-c", "sleep 5"]
