apiVersion: v1
kind: PersistentVolume
metadata:
    name: my-pv-150
spec:
    storageClassName: host-pv
    persistentVolumeReclaimPolicy: Delete
    capacity:
        storage: 150Mi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: "/my-pv/data/v1"
