apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: my-pvc
spec:
    accessModes:
        - ReadWriteMany
    storageClassName: host-pv
    resources:
        requests:
            storage: 10Mi
